name: Jest tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install -g pnpm@latest
      - name: Install modules
        run: pnpm i
      - name: Run tests
        run: pnpm jest
